version: '3'

services:
  mariadb:
    container_name: mariadb
    image : mariadb
    networks:
      - inception
    build:
      context: ./requirements/mariadb
      dockerfile: dockerfile
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - "3306"
    restart: on-failure
  
  nginx:
    container_name: nginx
    image : nginx
    networks :
      - inception
    depends_on:
      - wordpress
    build :
      context: requirements/nginx
      dockerfile: dockerfile
    volumes :
      - wordpress:/var/www/html
    env_file: 
      - .env
    ports:
    - 443:443
    restart : on-failure

  wordpress:
    container_name: wordpress
    image: wordpress
    networks:
      - inception
    build:
      context: ./requirements/wordpress
      dockerfile: dockerfile
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    depends_on :
      - mariadb
    restart: on-failure
    expose:
      - "9000"

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: '/home/vgoret/data/wordpress'
      o: bind
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: '/home/vgoret/data/mariadb'
      o: bind

networks:
  inception:
    driver: bridge