FROM debian:bullseye

RUN apt-get update -y
RUN apt-get upgrade -y
#check si deja installe
RUN apt-get install python3 -y 


RUN mkdir -p static_website data/website
COPY sources/ /static_website
COPY tools/copy.sh /data/website

CMD [ "sh", "/data/website/copy.sh" ]