FROM debian:bullseye

#MISE A JOUR
RUN apt update -y

#INSTALLATION DES PACKETS
RUN apt-get install mariadb-server -y

RUN mkdir -p var/run/mysqld && chown -R mysql:mysql /var/run/mysqld && chmod 755 /var/run/mysqld

COPY ./conf/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf

COPY ./conf/db_launch.sh /usr/local/bin/

RUN chmod 755 /usr/local/bin/db_launch.sh

EXPOSE 3306

ENTRYPOINT [ "sh", "/usr/local/bin/db_launch.sh" ]