FROM debian:bullseye

#MISE A JOUR
RUN apt-get -y update
RUN apt-get -y upgrade

#INSTALLATION DES PACKETS MARIADB
RUN apt-get install mariadb-server -y

# === PREPARATION DU DOSSIER DE MARIADB === #
#pour les fichiers de socket de le PID
RUN mkdir -p var/run/mysqld
#change le proprietaire du dossier pour que le server mariadb puisse y ecrire
RUN chown -R mysql:mysql /var/run/mysqld
RUN chmod 755 /var/run/mysqld

#COPIE LES FICHIERS DE CONF DANS LE CONTAINER
COPY conf/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf
COPY conf/db_launch.sh /usr/local/bin/db_launch.sh

#PERMISSIONS POUR LE SCRIPT DE CREATION DE LA DB
RUN chmod 777 /usr/local/bin/db_launch.sh

EXPOSE 3306

CMD [ "/usr/local/bin/db_launch.sh" ]