FROM debian:bullseye

#MISE A JOUR
RUN apt-get -y update
RUN apt-get -y upgrade

#INSTALLATION DES PACKETS MARIADB
RUN apt-get install mariadb-server -y

RUN mkdir -p var/run/mysqld
RUN chown -R mysql:mysql /var/run/mysqld
RUN chmod 755 /var/run/mysqld

COPY conf/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf
COPY conf/db_launch.sh /usr/local/bin/db_launch.sh

RUN chmod 777 /usr/local/bin/db_launch.sh

EXPOSE 3306

CMD [ "/usr/local/bin/db_launch.sh" ]