FROM debian:bullseye

#DOSSIER POUR STOCKER LES FICHIERS WP
RUN mkdir -p /var/www/html
#DOSSIER POUR STOCKER LES FICHIERS DE SOCKET DE PHP
RUN mkdir -p /run/php

#MISE A JOUR DES PACKETS
RUN apt-get update -y
RUN apt-get upgrade -y

#INSTALLATION DES PACKETS NEEDED
#WGET TO INSTALL WORDPRESS
RUN apt-get install wget -y
RUN apt-get install -y php7.4\
    php-fpm\
    php-mysql\
    php-common\
    php-cgi\
    php-cli\
    mariadb-client\
    unzip

#TO HAVE WORDPRESS IN DIRECTORY FORM
RUN wget http://fr.wordpress.org/wordpress-6.2.2-fr_FR.tar.gz -P /var/www
RUN cd /var/www && tar -xzf wordpress-6.2.2-fr_FR.tar.gz
RUN rm /var/www/wordpress-6.2.2-fr_FR.tar.gz

#TELECHARGEMENT DE WP.CLI POUR AUTO CONFIG
RUN cd /var/www/html && wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && chmod +x wp-cli.phar

#COPIE LES FICHIERS DE CONF DANS LE CONTAINER
COPY conf/www.conf /etc/php/7.4/fpm/pool.d/www.conf
COPY tools/wp-cli_autoconfig.sh /usr/local/bin/wp-cli_autoconfig.sh

#DONNE LES PERMS
RUN chmod +x /usr/local/bin/wp-cli_autoconfig.sh

#MANAGE TEMPLATE
COPY conf/retrogeek.0.7.zip /var/www/html/wp-content/themes/retrogeek.0.7.zip
RUN unzip /var/www/html/wp-content/themes/retrogeek.0.7.zip -d /var/www/html/wp-content/themes/
RUN rm /var/www/html/wp-content/themes/retrogeek.0.7.zip

EXPOSE 9000

ENTRYPOINT [ "sh", "/usr/local/bin/wp-cli_autoconfig.sh"]