FROM debian:bullseye

RUN mkdir -p /var/www/html
RUN mkdir -p /run/php

#MISE A JOUR DES PACKETS
RUN apt-get update -y
RUN apt-get upgrade -y

#INSTALLATION DES PACKETS NEEDED
#WGET TO INSTALL WORDPRESS
RUN apt install wget -y
RUN apt install -y php7.4 php-fpm php-mysql php-common php-cgi php-cli mariadb-client

EXPOSE 9000

#TO HAVE WORDPRESS IN DIRECTORY FORM
RUN wget http://fr.wordpress.org/wordpress-6.2.2-fr_FR.tar.gz -P /var/www
RUN cd /var/www && tar -xzf wordpress-6.2.2-fr_FR.tar.gz -C /var/www/.
RUN cp -r /var/www/wordpress/. /var/www/html
RUN rm /var/www/wordpress-6.2.2-fr_FR.tar.gz

RUN chown -R root:root /var/www/wordpress

RUN cd /var/www/html && wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && chmod +x wp-cli.phar

COPY conf/wordpress.conf /etc/php/7.4/fpm/pool.d/wordpress.conf

COPY tools/wp-cli_autoconfig.sh wp-cli_autoconfig.sh

RUN chmod +x wp-cli_autoconfig.sh

CMD [ "./wp-cli_autoconfig.sh"]